# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kishanvavdara',
                'doc_host': 'https://kishan5111.github.io',
                'git_url': 'https://github.com/kishan5111/kishanvavdara',
                'lib_path': 'kishanvavdara'},
  'syms': {'kishanvavdara.core': {'kishanvavdara.core.foo': ('core.html#foo', 'kishanvavdara/core.py')}}}
