project:
  type: website

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

website:
  search: false
  twitter-card:
    creator: "@kishanvavdara"
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Misc Resources"
        href: resources.qmd
    right:
      - icon: twitter
        href: https://twitter.com/kishanvavdara
      - icon: linkedin
        href: https://www.linkedin.com/in/kishan-vavdara-55680b190/
      - icon: github
        href: https://github.com/kishan5111
      - icon: rss
        href: blog/index.xml      

metadata-files: [nbdev.yml]